[package]
name = "moji"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.0"
console = "0.15.0"
clap = { version = "3.0", features = ["derive"] }
